# Generated by Django 5.2.7 on 2025-12-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled'), ('Landed', 'Landed')], default='Scheduled', max_length=20),
        ),
    ]
