# Generated by Django 5.2.7 on 2025-12-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passport',
            field=models.CharField(max_length=20),
        ),
    ]
